### ISSUE TITLE
AttributeError: 'module' object has no attribute 'cv'

### ISSUE THREAD

**Issue by JonnyAlpha** [piborg/monster-self-drive#1]
I have installed OpenCV 3.4.0. When running MonsterAuto.py I get the following error:

pi@raspberrypi:~/monster-self-drive $ ./MonsterAuto.py 
Libraries loaded
Running script in directory "."
TEST MODE: Skipping board setup
Setup camera input
Traceback (most recent call last):
  File "./MonsterAuto.py", line 91, in <module>
    Settings.capture.set(cv2.cv.CV_CAP_PROP_FRAME_WIDTH, Settings.imageWidth);
AttributeError: 'module' object has no attribute 'cv'

**Comment by piborg** [comment]
There are a few minor differences for OpenCV 3 vs OpenCv 2, it should be just a few minor changes to the code.

Try changing these lines:
```
Settings.capture.set(cv2.cv.CV_CAP_PROP_FRAME_WIDTH, Settings.imageWidth);
Settings.capture.set(cv2.cv.CV_CAP_PROP_FRAME_HEIGHT, Settings.imageHeight);
Settings.capture.set(cv2.cv.CV_CAP_PROP_FPS, Settings.frameRate);
```
to these ones:
```
Settings.capture.set(cv2.CV_CAP_PROP_FRAME_WIDTH, Settings.imageWidth);
Settings.capture.set(cv2.CV_CAP_PROP_FRAME_HEIGHT, Settings.imageHeight);
Settings.capture.set(cv2.CV_CAP_PROP_FPS, Settings.frameRate);
```

**Comment by JonnyAlpha** [comment]
Just tried that and received this:
pi@raspberrypi:~/monster-self-drive $ ./MonsterAuto.py 
Libraries loaded
Running script in directory "."
TEST MODE: Skipping board setup
Setup camera input
Traceback (most recent call last):
  File "./MonsterAuto.py", line 91, in <module>
    Settings.capture.set(cv2.CV_CAP_PROP_FRAME_WIDTH, Settings.imageWidth);
AttributeError: 'module' object has no attribute 'CV_CAP_PROP_FRAME_WIDTH'

I tried importing cv2 in both python and python3 and it only works with python2

**Comment by JonnyAlpha** [comment]
Resolved.
After a bit of research I found some info. If you drop the CV and change everything to:
Settings.capture.set(cv2.CAP_PROP_FRAME_WIDTH, Settings.imageWidth);
Settings.capture.set(cv2.CAP_PROP_FRAME_HEIGHT, Settings.imageHeight);
Settings.capture.set(cv2.CAP_PROP_FPS, Settings.frameRate);
It runs without and error.

**Comment by muhammad-faizan-122** [comment]
To calculate the frame width, height, and fps,
```
frame_width = int(cap.get(3))
frame_height = int(cap.get(4))
fps = int(cap.get(5))
```
